import type { GetStaticProps } from 'next'
import Head from 'next/head'
import { DataAndImage } from '../components/dataimage'
import { WeatherData, WeatherDescription } from '../data/weatherdata'
import { GenerateWeatherDescriptions } from '../helpers/generateweatherdescription'
import styles from '../styles/Home.module.css'

const GenerateWeather = (weather: WeatherData) => {
  const descriptions: WeatherDescription[] = GenerateWeatherDescriptions(weather);
  return descriptions.map((x,i) => {return <DataAndImage key={i} weatherdesc={x}/>})
}

const Home: React.FC<WeatherData> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.weathercontainer}>
        {GenerateWeather(props)}
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const weather = await new WeatherData(25, 2, 7, 0, 1);
  return { props: {...weather}};
}

export default Home
