import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import { DataAndImage } from '../components/dataimage'
import { WeatherData, WeatherDescription } from '../data/weatherdata'
import { GenerateWeatherDescriptions } from '../helpers/generateweatherdescription'
import { GenerateWeatherData } from '../services/weatherservice'
import styles from '../styles/Home.module.css'

const Home: React.FC<WeatherData> = (props) => {
  const GenerateWeather = (weather: WeatherData) => {
    const descriptions: WeatherDescription[] = GenerateWeatherDescriptions(weather);
    return descriptions.map((x,i) => {return <DataAndImage key={i} weatherdesc={x}/>})
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>{GenerateWeather(props)}</div>
    </div>
  )
}

export const getServerSideProps : GetServerSideProps<WeatherData> = async (context) => {
  const weather = await GenerateWeatherData();
  return { props: {...weather}};
}

export default Home
